if(NOT DEFINED SOURCE_DIR OR NOT DEFINED TARGET_DIR)
    message(FATAL_ERROR "Required parameters: SOURCE_DIR and TARGET_DIR")
endif()

file(GLOB_RECURSE SOURCE_FILES "${SOURCE_DIR}/*")
set(SOURCE_SIZE 0)
foreach(FILE IN LISTS SOURCE_FILES)
    if(EXISTS "${FILE}")
        file(SIZE "${FILE}" FILE_SIZE)
        math(EXPR SOURCE_SIZE "${SOURCE_SIZE} + ${FILE_SIZE}")
    endif()
endforeach()

set(TARGET_SIZE 0)
if(EXISTS "${TARGET_DIR}")
    file(GLOB_RECURSE TARGET_FILES "${TARGET_DIR}/*")
    foreach(FILE IN LISTS TARGET_FILES)
        if(EXISTS "${FILE}")
            file(SIZE "${FILE}" FILE_SIZE)
            math(EXPR TARGET_SIZE "${TARGET_SIZE} + ${FILE_SIZE}")
        endif()
    endforeach()
endif()

if(NOT SOURCE_SIZE EQUAL TARGET_SIZE)
    file(COPY "${SOURCE_DIR}/" DESTINATION "${TARGET_DIR}")
    message(STATUS "Update assets folder (size: ${SOURCE_SIZE} bytes)")
endif()
