load("@rules_cc//cc:cc_binary.bzl", "cc_binary")

cc_binary(
    name = "Simulacrum",
    srcs = [
        "Main.cpp",
        "Engine.cpp",
        "GPUDevice.cpp",
        "GPURenderer.cpp",
        "InputManager.cpp",
        "ResourcePath.cpp",
        "SettingsManager.cpp",
        "TimestepManager.cpp",
    ],
    hdrs = [
        "Engine.hpp",
        "GPUDevice.hpp",
        "GPURenderer.hpp",
        "InputManager.hpp",
        "ResourcePath.hpp",
        "SettingsManager.hpp",
        "ThreadSystem.hpp",
        "TimestepManager.hpp",
    ],
)
