function(print_project_info TARGET_NAME)
    message(STATUS "")
    message(STATUS "==============================================")
    message(STATUS "Project configuration complete!")
    message(STATUS " Target Name:  ${TARGET_NAME}")
    message(STATUS " C++ Standard: ${CMAKE_CXX_STANDARD}")
    message(STATUS " CMake Source: ${CMAKE_SOURCE_DIR}")

    if(CMAKE_RUNTIME_OUTPUT_DIRECTORY)
        message(STATUS "  Executable output: ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}")
    else()
        if(CMAKE_CONFIGURATION_TYPES)
            message(STATUS "  Executable output: ${CMAKE_BINARY_DIR}/<Configuration Name> (e.g. Debug/Release)")
        else()
            message(STATUS "  Executable output: ${CMAKE_BINARY_DIR}")
        endif()
    endif()

    message(STATUS "  Smart dependency retrieval: Prebuilt (prebuild directory) > System libraries > Local source code (external directory) > Online retrieval")

    if(BUILD_SHARED_LIBS)
        message(STATUS "  Default linking for dependency libraries: Dynamically linked (Shared)")
    else()
        message(STATUS "  Default linking for dependency libraries: Statically linked (Static)")
    endif()

    if(WIN32)
        message(STATUS "  Runtime library handling: Automatically detects and copies all DLLs to the exe directory")
        if(MSVC)
            message(STATUS "  Character encoding: UTF-8")
        endif()
    elseif(APPLE)
        message(STATUS "  Runtime library handling: Using RPATH (@executable_path)")
    elseif(UNIX)
        message(STATUS "  Runtime library handling: Using RPATH ($ORIGIN)")
    endif()

    message(STATUS "==============================================")
    message(STATUS "")
endfunction()